### ISSUE TITLE
Relabel Python wrappers

### ISSUE THREAD

**Issue by simbs** [WPTechInnovation/worldpay-within-sdk#129] opened 2017-02-12 21:07 UTC
The Python wrappers should be labeled by which thrift they use, not Python version, since the thriftpy one works with 2.x and 3.x. The main difference is that one uses thrift's python generator, and the other uses thriftpy.

@kevingordonwp do you agree?

**Comment by kevingordonwp** [comment] 2017-02-12 22:28
I like it! The proposal is to call them python_apachethrift and python_thriftpy ?

**Comment by kevingordonwp** [comment] 2017-02-12 22:29
Need Conor's input as gatekeeper too @chackett thoughts?

**Comment by simbs** [comment] 2017-02-12 22:34
👍 for the naming

**Comment by andybrodie** [comment] 2017-02-13 07:31
What's the reason for maintaining both an Apache Thrift and a ThriftPy version of the wrapper?  Purely from a maintenance perspective, do we need to maintain (I guess) 3 versions of a Python wrapper?

**Comment by simbs** [comment] 2017-02-13 13:30
@andybrodie you mean 2 versions?

When I started working on the python wrapper the apache version didn't work with Python3, so I used thriftpy instead. I only recently tested that it works with Python2. But this is, in principle, an open source project, so if in the future we don't maintain a wrapper, people who need it should be able to update it to the most recent spec. I don't think maintenance should be a concern.

I've seen there's been some improvements on the Python3 support for apache thrift, and I'll look into making that wrapper compatible with both Pythons as well.

**Comment by andybrodie** [comment] 2017-02-13 15:21
I originally thought 3:

1. Apache Thrift for Python 2.x
2. Apache Thrift for Python 3.x
3. ThriftPy for Python 2.x & 3.x

But sounds like having a wrapper compatible with both is on your todo list already (if not already done!)

I was curious as to whether we needed both Apache and Thriftpy, even though it's open source I think we should either maintain or deprecate/remove once we've decided to not continue maintenance - perhaps it should be moved to a separate repo.  It would be frustrating for a developer to download the latest SDK then download the corresponding wrapper and find that it doesn't work because the SDK has moved on.

**Comment by simbs** [comment] 2017-02-13 16:21
@andybrodie see #128 for the second part of your comment

**Comment by chackett** [comment] 2017-02-20 02:24
Just seeing this now.

So, I am unsure as to why we need a second wrapper if one of them will support both Python 2.x and 3.x. It also represents duplication of effort which seems inefficient to me and I would like to think the developer resource could be put to better use elsewhere.

For me, my first preference would be the official Apache implementation of Thrift for Python. They were obviously slow to implement support for 3.x and so the community stepped in to provide support in the form of Thriftpy.

I've found the official ticket for Python  support [here](https://issues.apache.org/jira/browse/THRIFT-1857). It looks like this is now implemented and supported. Going forward any issues _should_ be small and _should_ get patched quickly. Considering this, I propose we investigate this update with a view to dropping the Thriftpy implementation. [that said, the ticket is 3 years old :/]

That said, if the community based Thriftpy works for our needs then I think we should stick with that. By design Thrift is abstracted in the wrappers, meaning we should be easily able to switch implementations later without any major stress to implementers.

To quote @simbs
`But this is, in principle, an open source project, so if in the future we don't maintain a wrapper, people who need it should be able to update it to the most recent spec. I don't think maintenance should be a concern.`

I don't think that's the spirit of open source, if your going to host some code then I think you should at least maintain it. People who seek out libraries, sdks etc expect them to be readily available and functional, they shouldn't have to update / fix to get a working version. If I came across something that was out of date due to lack of maintenance then I would steer clear. In fact, when selecting open source libraries for use in a project one of the key indicators of quality is "active maintenance" as a matter of best practice.

I think if we are going to host an opensource repository then maintenance is absolutely a concern, unless we clearly mark it as deprecated, in which case developers use at their peril.

**Comment by kevingordonwp** [comment] 2017-04-07 10:58
Hi all @simbs and I realise the python 3.x version supports 2.x versions... So we've agreed to decommission 2.7 version and focus on just the 3.x version.

**Comment by kevingordonwp** [comment] 2017-08-22 22:39
We've now consolidated down to a single repo for Python: https://github.com/WPTechInnovation/wpw-sdk-python so I'm closing this issue.

**Closed by kevingordonwp** 2017-08-22 22:39 UTC
Labels: enhancement, question
